# Generated by Django 3.1.1 on 2020-09-27 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatfuncs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='chatfuncs.chat'),
        ),
    ]
