# Generated by Django 3.1.1 on 2020-10-05 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatfuncs', '0002_auto_20200927_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_whom', models.CharField(max_length=250)),
                ('islike', models.BooleanField(default=True)),
                ('parentchat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likeDislikeList', to='chatfuncs.chat')),
            ],
        ),
    ]
